name: Generate REAME.md

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 */3 * * *'

jobs:
  build:

    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        go-version: [1.14.x]
        platform: [ubuntu-latest]

    steps:
      - name: Configure git for private modules
        env:
          TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: git config --global url."https://${GITHUB_ACTOR}:${TOKEN}@github.com".insteadOf "https://github.com"

      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      # - name: Series of Tests
      #   run: |
      #     go test ./...
      #     go test -race ./...

      - name: Generate README
        run: go run main.go

      - name: Commit README
        run: |
    
          git add .
          git commit -m 'refresh list'
          git push
